# Generated by Django 4.2.3 on 2023-07-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='image/')),
                ('Wallpaper', models.ImageField(upload_to='walls/')),
                ('color', models.CharField(choices=[('GAMES', 'Games'), ('NATURE', 'Nature'), ('ABSTRACT', 'Abstract'), ('CARS', 'Cars'), ('CITY', 'City'), ('MOVIES', 'Movies'), ('SPACE', 'Space'), ('RANDOM', 'Random')], default='Random', max_length=10)),
            ],
        ),
    ]
