# Generated by Django 4.2.3 on 2023-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0002_rename_color_wallpaper_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
