# Generated by Django 4.2.3 on 2023-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.CharField(choices=[('GAMES', 'Games'), ('NATURE', 'Nature'), ('ABSTRACT', 'Abstract'), ('CARS', 'Cars'), ('ANIMALS', 'Animals'), ('MOVIES', 'Movies'), ('SPACE', 'Space'), ('RANDOM', 'Random')], default='Random', max_length=10),
        ),
    ]
