# Generated by Django 4.2.3 on 2023-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0006_alter_wallpaper_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.CharField(choices=[('GAMES', 'Games'), ('NATURE', 'Nature'), ('ABSTRACT', 'Abstract'), ('CARS', 'Cars'), ('ANIMALS', 'Animals'), ('ARCHITECTURE', 'Architecture'), ('SPACE', 'Space'), ('RANDOM', 'Random')], default='Random', max_length=15),
        ),
    ]
