# Generated by Django 4.2.3 on 2023-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0008_rename_wallpaper_wallpaper_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveWalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('clip', models.FileField(upload_to='clips/')),
                ('live_wall', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
